added hamcrest-core as test dependency of spock-spring because otherwise we sometimes get NoClassDefFoundError for org.hamcrest.SelfDescribing (after switching to junit-dep); suspicous